TCA: Add SCM (Secure Channel Manager) architecture extension explicitly
The versions of the ARM assembler contained in the android toolchain
arm-eabi-4.6 requires adding an architecture extension explicitly before
using the corresponding instructions.

This commit resolves the following compile error in drivers/misc/tzic.c:
Error: selected processor does not support ARM mode `smc 0'